#!/bin/bash
#SBATCH -J 1
#SBATCH -N 1
#SBATCH -t 1:00:00
#SBATCH --partition=short
#SBATCH --ntasks-per-node=24
#SBATCH --output=%job.stdout
#SBATCH --error=%job.stderr

#python3 qmwork_dftb_singleatom.py
#python3 qmwork_dftb_optimization_p.py
#python3 qmwork_dftb_optimization.py
# python3 qmwork_dftb_single.py
python3 qmwork_adf_optimization.py
